// Academy Courses Data - Version complète détaillée
export interface Lesson {
  id: number
  title: string
  duration: string
  videoUrl?: string
  description: string
  isFree?: boolean
}

export interface Course {
  id: number
  slug: string
  number: string
  title: string
  duration: string
  modules: number
  students: number
  description: string
  longDescription: string
  icon: string
  color: string
  difficulty: string
  resources: { name: string; url: string; type: string }[]
  lessons: Lesson[]
  instructor: string
  instructorBio: string
  lastUpdated: string
  whatYouLearn: string[]
  requirements: string[]
}

export const ACADEMY_COURSES: Course[] = [
  {
    id: 1,
    slug: 'premier-stream',
    number: '01',
    title: 'Préparer son Premier Stream',
    duration: '45 min',
    modules: 12,
    students: 15420,
    description: 'De zéro à ton premier live : mindset, matériel minimum, choix de plateforme',
    longDescription: `Ce cours complet te guide pas à pas pour lancer ton premier stream avec succès. Tu apprendras à choisir la bonne plateforme (Twitch, YouTube, TikTok), à configurer ton matériel de base, et à adopter le bon état d'esprit pour débuter sereinement.

Que tu aies un budget serré ou un setup plus conséquent, ce cours t'accompagne pour faire les meilleurs choix et éviter les erreurs de débutant. À la fin, tu seras prêt(e) à appuyer sur "Go Live" avec confiance !`,
    icon: 'Play',
    color: 'from-emerald-400 via-green-500 to-teal-600',
    difficulty: 'Débutant',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Décembre 2025',
    whatYouLearn: [
      'Choisir la meilleure plateforme pour ton contenu',
      'Configurer ton matériel de streaming de A à Z',
      'Créer une chaîne attractive dès le départ',
      'Gérer le stress du premier live',
      'Interagir efficacement avec ton chat',
      'Analyser tes performances après chaque stream',
    ],
    requirements: [
      'Un ordinateur avec connexion internet',
      'Un micro (même intégré au début)',
      'De la motivation et de la patience !',
    ],
    resources: [
      { name: 'Checklist Premier Stream', url: '/downloads/checklist-premier-stream.md', type: 'PDF' },
      { name: 'Template de Planning Hebdo', url: '/downloads/template-planning-hebdo.csv', type: 'Excel' },
      { name: 'Script de Présentation', url: '/downloads/script-presentation.md', type: 'Doc' },
      { name: 'Guide des Meilleurs Créneaux Horaires', url: '/downloads/guide-creneaux-horaires.md', type: 'PDF' },
      { name: 'Fiche Récap Matériel Débutant', url: '/downloads/fiche-materiel-debutant.md', type: 'PDF' },
    ],
    lessons: [
      { id: 1, title: 'Introduction : Bienvenue dans le monde du streaming', duration: '3 min', description: 'Découvre ce qui t\'attend dans ce cours et comment en tirer le maximum', isFree: true },
      { id: 2, title: 'Pourquoi streamer en 2025 ?', duration: '5 min', description: 'Les opportunités du streaming et pourquoi c\'est le bon moment de se lancer' },
      { id: 3, title: 'Twitch vs YouTube vs TikTok : Quelle plateforme choisir ?', duration: '8 min', description: 'Analyse comparative détaillée des forces et faiblesses de chaque plateforme' },
      { id: 4, title: 'Les autres plateformes à considérer', duration: '4 min', description: 'Kick, Facebook Gaming, Trovo : les alternatives à connaître' },
      { id: 5, title: 'Le matériel minimum pour commencer', duration: '6 min', description: 'Webcam, micro, PC : les essentiels sans se ruiner' },
      { id: 6, title: 'Setup complet pour moins de 100€', duration: '5 min', description: 'Liste d\'achats optimisée pour petit budget' },
      { id: 7, title: 'Créer son compte et configurer son profil', duration: '5 min', description: 'Optimise ta chaîne pour attirer tes premiers viewers' },
      { id: 8, title: 'Choisir son identité visuelle', duration: '4 min', description: 'Avatar, bannière, couleurs : créer une marque cohérente' },
      { id: 9, title: 'Le mindset du streamer débutant', duration: '4 min', description: 'Gérer le stress et les attentes réalistes' },
      { id: 10, title: 'Planifier son premier stream', duration: '5 min', description: 'Date, heure, durée : les bonnes pratiques qui marchent' },
      { id: 11, title: 'Préparer son contenu : que faire pendant le live ?', duration: '6 min', description: 'Structurer son stream pour ne jamais s\'ennuyer' },
      { id: 12, title: 'Les 10 erreurs à éviter absolument', duration: '5 min', description: 'Les pièges classiques des débutants et comment les éviter' },
      { id: 13, title: 'Checklist technique avant le live', duration: '3 min', description: 'Les vérifications essentielles pour un stream sans problème' },
      { id: 14, title: 'C\'est parti ! Ton premier "Go Live"', duration: '4 min', description: 'Les derniers conseils avant de cliquer sur le bouton' },
      { id: 15, title: 'Interagir avec ton chat efficacement', duration: '4 min', description: 'Les bases de l\'engagement communautaire' },
      { id: 16, title: 'Gérer les imprévus techniques', duration: '3 min', description: 'Que faire quand ça plante ? Guide de survie' },
      { id: 17, title: 'Après le stream : analyse et amélioration', duration: '4 min', description: 'Comment progresser à chaque session' },
      { id: 18, title: 'Conclusion et prochaines étapes', duration: '2 min', description: 'Ton plan d\'action pour les 30 prochains jours' },
    ],
  },
  {
    id: 2,
    slug: 'obs-studio',
    number: '02',
    title: 'OBS Studio Masterclass',
    duration: '2h 30min',
    modules: 24,
    students: 23891,
    description: 'Maîtrise complète : scènes, sources, filtres, transitions, encodage optimal',
    longDescription: `Deviens un expert d'OBS Studio avec cette masterclass complète. De l'installation à la configuration avancée, tu maîtriseras tous les aspects de ce logiciel incontournable utilisé par 90% des streamers.

Tu apprendras à créer des scènes professionnelles, configurer tes sources audio/vidéo parfaitement, appliquer des filtres avancés pour une qualité broadcast, créer des transitions fluides, et surtout optimiser ton encodage pour streamer en haute qualité sans lag ni frame drops.`,
    icon: 'Video',
    color: 'from-cyan-400 via-blue-500 to-indigo-600',
    difficulty: 'Intermédiaire',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Décembre 2025',
    whatYouLearn: [
      'Maîtriser l\'interface OBS comme un pro',
      'Créer des scènes complexes multi-sources',
      'Configurer l\'audio parfaitement (plus de bruit !)',
      'Appliquer des filtres vidéo professionnels',
      'Optimiser l\'encodage pour ta config',
      'Utiliser les plugins essentiels',
      'Résoudre 95% des problèmes courants',
    ],
    requirements: [
      'OBS Studio installé (gratuit)',
      'Un PC capable de streamer',
      'Avoir suivi le Module 01 ou équivalent',
    ],
    resources: [
      { name: 'Pack Scene Collections Pro', url: '#', type: 'ZIP' },
      { name: 'Profils d\'encodage par GPU', url: '#', type: 'JSON' },
      { name: 'Cheatsheet Raccourcis OBS', url: '#', type: 'PDF' },
      { name: 'Guide Filtres Audio Complet', url: '#', type: 'PDF' },
      { name: 'Templates Transitions Stinger', url: '#', type: 'ZIP' },
      { name: 'Script Browser Sources', url: '#', type: 'HTML' },
    ],
    lessons: [
      { id: 1, title: 'Installation et premier lancement d\'OBS', duration: '5 min', description: 'Configuration initiale optimale', isFree: true },
      { id: 2, title: 'Tour complet de l\'interface', duration: '8 min', description: 'Comprendre chaque élément d\'OBS' },
      { id: 3, title: 'Créer ta première scène', duration: '6 min', description: 'Les bases des scènes OBS' },
      { id: 4, title: 'Les différents types de sources', duration: '10 min', description: 'Capture d\'écran, fenêtre, jeu, navigateur...' },
      { id: 5, title: 'Ajouter et configurer ta webcam', duration: '7 min', description: 'Résolution, FPS, couleurs' },
      { id: 6, title: 'Capture de jeu : la méthode parfaite', duration: '8 min', description: 'Éviter les écrans noirs et les lags' },
      { id: 7, title: 'Sources audio : micro et desktop', duration: '7 min', description: 'Configuration audio professionnelle' },
      { id: 8, title: 'Le mixeur audio avancé', duration: '6 min', description: 'Gérer plusieurs sources audio' },
      { id: 9, title: 'Filtres audio : Noise Gate', duration: '5 min', description: 'Éliminer les bruits de fond' },
      { id: 10, title: 'Filtres audio : Compresseur', duration: '5 min', description: 'Équilibrer le volume automatiquement' },
      { id: 11, title: 'Filtres audio : Noise Suppression et EQ', duration: '6 min', description: 'Son broadcast professionnel' },
      { id: 12, title: 'Filtres vidéo : Correction couleurs', duration: '8 min', description: 'LUT, balance, saturation' },
      { id: 13, title: 'Filtres vidéo : Chroma Key (fond vert)', duration: '7 min', description: 'Supprimer ton fond parfaitement' },
      { id: 14, title: 'Filtres vidéo : Masques et cropping', duration: '5 min', description: 'Découper et masquer tes sources' },
      { id: 15, title: 'Créer plusieurs scènes', duration: '6 min', description: 'Scène jeu, just chatting, BRB, etc.' },
      { id: 16, title: 'Transitions entre scènes', duration: '5 min', description: 'Fade, slide, stinger personnalisé' },
      { id: 17, title: 'Studio Mode : switcher comme un pro', duration: '4 min', description: 'Prévisualiser avant de passer en live' },
      { id: 18, title: 'Paramètres d\'encodage : théorie', duration: '8 min', description: 'Comprendre bitrate, preset, keyframe' },
      { id: 19, title: 'x264 vs NVENC vs AMF vs QuickSync', duration: '10 min', description: 'Choisir le bon encodeur pour ta config' },
      { id: 20, title: 'Optimiser pour Twitch', duration: '6 min', description: 'Les meilleurs réglages pour Twitch' },
      { id: 21, title: 'Optimiser pour YouTube', duration: '5 min', description: 'Paramètres spécifiques YouTube' },
      { id: 22, title: 'Raccourcis clavier essentiels', duration: '5 min', description: 'Productivité maximale' },
      { id: 23, title: 'Les plugins indispensables', duration: '10 min', description: 'StreamFX, Move Transition, Browser...' },
      { id: 24, title: 'Dépannage : résoudre les problèmes courants', duration: '8 min', description: 'Lag, frame drops, audio désync...' },
      { id: 25, title: 'OBS sur 2 PC : le setup NDI', duration: '6 min', description: 'Configuration dual PC streaming' },
      { id: 26, title: 'Conclusion et ressources', duration: '3 min', description: 'Récap et prochaines étapes' },
    ],
  },
  {
    id: 3,
    slug: 'overlays-design',
    number: '03',
    title: 'Overlays & Design Pro',
    duration: '1h 45min',
    modules: 16,
    students: 19234,
    description: 'Crée des overlays uniques avec Photoshop, Figma, After Effects',
    longDescription: `Transforme ton stream avec des overlays professionnels créés par toi-même. Ce cours te guide pour designer des éléments visuels uniques qui reflètent parfaitement ton identité de marque.

Tu apprendras à utiliser Photoshop, Figma (gratuit !) et After Effects pour créer des overlays gaming, des alertes animées, des écrans de pause, et des panneaux Twitch qui impressionneront ton audience et te démarqueront de la masse.`,
    icon: 'Sparkles',
    color: 'from-violet-400 via-purple-500 to-fuchsia-600',
    difficulty: 'Avancé',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Novembre 2025',
    whatYouLearn: [
      'Principes de design pour le streaming',
      'Créer des overlays pro dans Photoshop',
      'Designer gratuitement avec Figma',
      'Animer tes éléments avec After Effects',
      'Créer des écrans BRB, Starting, Ending',
      'Concevoir des alertes animées uniques',
      'Exporter correctement pour OBS',
    ],
    requirements: [
      'Photoshop (ou alternative gratuite)',
      'Figma (gratuit)',
      'After Effects (optionnel)',
      'Notions de base en design',
    ],
    resources: [
      { name: 'Pack 50 Overlays PSD Éditables', url: '#', type: 'PSD' },
      { name: 'Templates Figma Complets', url: '#', type: 'Figma' },
      { name: 'Projet After Effects Alertes', url: '#', type: 'AEP' },
      { name: 'Assets Graphiques (500+)', url: '#', type: 'ZIP' },
      { name: 'Pack Fonts Gaming Gratuits', url: '#', type: 'ZIP' },
      { name: 'Palette de Couleurs Neon', url: '#', type: 'ASE' },
    ],
    lessons: [
      { id: 1, title: 'Principes du design pour streamers', duration: '6 min', description: 'Les règles d\'or pour un design efficace', isFree: true },
      { id: 2, title: 'Créer ta charte graphique', duration: '8 min', description: 'Couleurs, fonts, style cohérent' },
      { id: 3, title: 'Les formats et résolutions à connaître', duration: '4 min', description: 'Bien dimensionner tes éléments' },
      { id: 4, title: 'Photoshop : interface et outils essentiels', duration: '10 min', description: 'Tour complet pour débutants' },
      { id: 5, title: 'Créer un overlay webcam de A à Z', duration: '15 min', description: 'Cadre webcam professionnel' },
      { id: 6, title: 'Barre d\'informations lower third', duration: '10 min', description: 'Nom, réseaux, événements' },
      { id: 7, title: 'Overlay gaming complet', duration: '12 min', description: 'Chat, events, webcam intégrés' },
      { id: 8, title: 'Figma : l\'alternative gratuite puissante', duration: '8 min', description: 'Prise en main complète' },
      { id: 9, title: 'Créer un overlay dans Figma', duration: '12 min', description: 'Méthode moderne et collaborative' },
      { id: 10, title: 'Exporter correctement pour OBS', duration: '5 min', description: 'PNG transparent, optimisation' },
      { id: 11, title: 'Écran Starting Soon animé', duration: '10 min', description: 'Compte à rebours stylé' },
      { id: 12, title: 'Écran BRB (Be Right Back)', duration: '8 min', description: 'Pause screen professionnel' },
      { id: 13, title: 'Écran de fin Ending', duration: '6 min', description: 'Terminer en beauté' },
      { id: 14, title: 'After Effects : bases de l\'animation', duration: '12 min', description: 'Donner vie à tes éléments' },
      { id: 15, title: 'Créer une alerte Follow animée', duration: '10 min', description: 'Animation with sound' },
      { id: 16, title: 'Alertes Sub, Donation, Raid', duration: '12 min', description: 'Pack alertes complet' },
      { id: 17, title: 'Panneaux Twitch (About, Rules, etc.)', duration: '8 min', description: 'Designer ta page chaîne' },
      { id: 18, title: 'Emotes et badges sub', duration: '8 min', description: 'Créer tes propres emotes' },
      { id: 19, title: 'Bannière et avatar cohérents', duration: '6 min', description: 'Identité visuelle complète' },
      { id: 20, title: 'Conclusion et récap', duration: '3 min', description: 'Tes prochains projets' },
    ],
  },
  {
    id: 4,
    slug: 'alerts-soundboard',
    number: '04',
    title: 'Alerts & Soundboard',
    duration: '1h 15min',
    modules: 10,
    students: 17652,
    description: 'Streamlabs, StreamElements, alertes custom, soundboard épique',
    longDescription: `Crée une expérience interactive unique avec des alertes personnalisées et un soundboard qui fera réagir ton chat à chaque moment clé de ton stream.

Ce cours couvre toutes les plateformes d'alertes populaires : Streamlabs, StreamElements, et même des solutions custom. Tu apprendras à créer des alertes CSS personnalisées, configurer des variations, et mettre en place un soundboard professionnel pour des streams dynamiques.`,
    icon: 'Zap',
    color: 'from-orange-400 via-amber-500 to-yellow-500',
    difficulty: 'Intermédiaire',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Décembre 2025',
    whatYouLearn: [
      'Configurer Streamlabs parfaitement',
      'Maîtriser StreamElements',
      'Créer des alertes CSS custom',
      'Configurer des variations d\'alertes',
      'Mettre en place un soundboard pro',
      'Créer des interactions chat uniques',
    ],
    requirements: [
      'Compte Streamlabs ou StreamElements',
      'OBS Studio configuré (Module 02)',
      'Des sons à utiliser (fournis dans les ressources)',
    ],
    resources: [
      { name: 'Pack 100 Sons Libres de Droits', url: '#', type: 'MP3' },
      { name: 'Code CSS Alertes Premium', url: '#', type: 'CSS' },
      { name: 'Templates Widget Custom', url: '#', type: 'HTML' },
      { name: 'Guide Soundpad Complet', url: '#', type: 'PDF' },
      { name: 'Pack Sons Memes', url: '#', type: 'ZIP' },
      { name: 'Alertes Vidéo WebM', url: '#', type: 'ZIP' },
    ],
    lessons: [
      { id: 1, title: 'Introduction aux alertes de stream', duration: '4 min', description: 'Pourquoi les alertes sont cruciales', isFree: true },
      { id: 2, title: 'Streamlabs vs StreamElements : le comparatif', duration: '8 min', description: 'Forces et faiblesses de chaque plateforme' },
      { id: 3, title: 'Configuration Streamlabs de A à Z', duration: '12 min', description: 'Setup complet pas à pas' },
      { id: 4, title: 'Configuration StreamElements', duration: '10 min', description: 'Alternative puissante et gratuite' },
      { id: 5, title: 'Personnaliser ses alertes (sans code)', duration: '8 min', description: 'Images, sons, animations natives' },
      { id: 6, title: 'Les bases du CSS pour alertes', duration: '10 min', description: 'Modifier le style de tes alertes' },
      { id: 7, title: 'Créer une alerte CSS from scratch', duration: '15 min', description: 'Alerte 100% personnalisée' },
      { id: 8, title: 'Variations d\'alertes (montants différents)', duration: '8 min', description: 'Alertes différentes selon le don' },
      { id: 9, title: 'Alertes vidéo avec WebM', duration: '6 min', description: 'Animations vidéo transparentes' },
      { id: 10, title: 'Configurer un Soundboard simple', duration: '8 min', description: 'Premiers pas avec les sons' },
      { id: 11, title: 'Soundpad : le logiciel pro', duration: '10 min', description: 'Configuration avancée' },
      { id: 12, title: 'Créer des Channel Points rewards sonores', duration: '8 min', description: 'Sons déclenchés par le chat' },
      { id: 13, title: 'TTS (Text-to-Speech) configuration', duration: '6 min', description: 'Faire parler les donations' },
      { id: 14, title: 'Intégration dans OBS', duration: '5 min', description: 'Browser source parfaitement configurée' },
      { id: 15, title: 'Dépannage des alertes', duration: '5 min', description: 'Résoudre les problèmes courants' },
      { id: 16, title: 'Bonus : les bots pour alertes custom', duration: '6 min', description: 'Aller encore plus loin' },
    ],
  },
  {
    id: 5,
    slug: 'multistream-regie',
    number: '05',
    title: 'Multistream & Régie',
    duration: '1h 30min',
    modules: 14,
    students: 12843,
    description: 'Streamer sur Twitch + YouTube + TikTok simultanément comme un pro',
    longDescription: `Maximise ta portée en diffusant sur plusieurs plateformes simultanément sans violer les règles de Twitch. Ce cours te montre comment gérer une vraie régie de streaming professionnelle.

Tu découvriras les outils de multistream (Restream, Owncast), apprendras à gérer plusieurs chats unifiés, et maîtriseras les techniques de régie broadcast pour des productions dignes de la télévision. Parfait pour les événements, les tournois, ou simplement pour toucher plus de monde.`,
    icon: 'Users',
    color: 'from-pink-400 via-rose-500 to-red-500',
    difficulty: 'Avancé',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Novembre 2025',
    whatYouLearn: [
      'Streamer sur plusieurs plateformes légalement',
      'Configurer Restream.io parfaitement',
      'Gérer plusieurs chats en un seul endroit',
      'Techniques de régie professionnelle',
      'Setup RTMP custom avancé',
      'Organiser un stream à plusieurs caméras',
    ],
    requirements: [
      'OBS Studio niveau intermédiaire',
      'Connexion internet stable (min 20 Mbps upload)',
      'Compte sur au moins 2 plateformes',
    ],
    resources: [
      { name: 'Guide Complet Restream.io', url: '#', type: 'PDF' },
      { name: 'Configuration RTMP Custom', url: '#', type: 'TXT' },
      { name: 'Comparatif Outils Multistream', url: '#', type: 'Excel' },
      { name: 'Template Rundown Event', url: '#', type: 'Doc' },
      { name: 'Script Régie Type', url: '#', type: 'PDF' },
      { name: 'Liste Matériel Régie Budget', url: '#', type: 'PDF' },
    ],
    lessons: [
      { id: 1, title: 'Pourquoi faire du multistream ?', duration: '5 min', description: 'Avantages, inconvénients et légalité', isFree: true },
      { id: 2, title: 'Les règles Twitch sur le simulcast', duration: '6 min', description: 'Ce qui est autorisé ou non' },
      { id: 3, title: 'Configuration Restream.io', duration: '12 min', description: 'Setup complet pas à pas' },
      { id: 4, title: 'Gérer le chat unifié avec Restream', duration: '8 min', description: 'Tous les chats en un seul endroit' },
      { id: 5, title: 'Alternative : Owncast (self-hosted)', duration: '10 min', description: 'Solution 100% libre' },
      { id: 6, title: 'Setup RTMP custom avancé', duration: '8 min', description: 'Pour les configurations complexes' },
      { id: 7, title: 'Multistream depuis OBS directement', duration: '6 min', description: 'Sans service externe' },
      { id: 8, title: 'Gérer plusieurs chats : les bots', duration: '8 min', description: 'Streamcord, Fossabot cross-platform' },
      { id: 9, title: 'Introduction à la régie broadcast', duration: '6 min', description: 'Vocabulaire et concepts' },
      { id: 10, title: 'Setup multi-caméras', duration: '10 min', description: 'Plusieurs angles comme à la TV' },
      { id: 11, title: 'Utiliser un stream deck comme régie', duration: '8 min', description: 'Contrôle tactile professionnel' },
      { id: 12, title: 'Transitions et replay instantané', duration: '8 min', description: 'Techniques broadcast avancées' },
      { id: 13, title: 'Organiser un événement en direct', duration: '10 min', description: 'Tournoi, marathon, charity' },
      { id: 14, title: 'Gérer une équipe de régie', duration: '6 min', description: 'Coordination multi-personnes' },
      { id: 15, title: 'Optimiser le débit pour multistream', duration: '5 min', description: 'Qualité sans saturer ta connexion' },
      { id: 16, title: 'Conclusion et cas d\'usage', duration: '4 min', description: 'Quand utiliser le multistream' },
    ],
  },
  {
    id: 6,
    slug: 'monetisation',
    number: '06',
    title: 'Monétisation 360°',
    duration: '2h 00min',
    modules: 18,
    students: 21093,
    description: 'Subs, bits, dons, sponsors, affiliation Amazon, YouTube Revenue',
    longDescription: `Transforme ta passion en revenus avec ce guide complet de la monétisation. Découvre TOUTES les sources de revenus possibles pour un streamer en 2025.

Des subs Twitch à l'affiliation Amazon, des sponsors aux dons PayPal, en passant par Patreon et le merch, tu auras une vision à 360° pour construire un business durable autour de ton contenu. Inclut des templates de contrats et un simulateur de revenus.`,
    icon: 'Trophy',
    color: 'from-lime-400 via-green-500 to-emerald-600',
    difficulty: 'Expert',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Décembre 2025',
    whatYouLearn: [
      'Toutes les sources de revenus possibles',
      'Devenir Affiliate puis Partner Twitch',
      'Maximiser subs, bits et donations',
      'Programme d\'affiliation Amazon',
      'Trouver et négocier des sponsors',
      'Créer et vendre du merchandising',
      'Diversifier avec Patreon et YouTube',
    ],
    requirements: [
      'Avoir déjà streamé plusieurs fois',
      'Comprendre les bases du streaming',
      'Être prêt à traiter le streaming comme un business',
    ],
    resources: [
      { name: 'Simulateur de Revenus Excel', url: '#', type: 'Excel' },
      { name: 'Template Contrat Sponsor', url: '#', type: 'Doc' },
      { name: 'Liste 200+ Sponsors Gaming', url: '#', type: 'PDF' },
      { name: 'Guide Affiliation Amazon', url: '#', type: 'PDF' },
      { name: 'Media Kit Template', url: '#', type: 'PSD' },
      { name: 'Calculateur Tarifs Sponsor', url: '#', type: 'Excel' },
    ],
    lessons: [
      { id: 1, title: 'Tour d\'horizon de la monétisation', duration: '6 min', description: 'Toutes les sources de revenus possibles', isFree: true },
      { id: 2, title: 'Mindset : traiter le stream comme un business', duration: '5 min', description: 'L\'état d\'esprit qui fait la différence' },
      { id: 3, title: 'Devenir Affiliate Twitch : les conditions', duration: '8 min', description: 'Requirements et processus' },
      { id: 4, title: 'De Affiliate à Partner : la roadmap', duration: '8 min', description: 'Les étapes pour Partner' },
      { id: 5, title: 'Optimiser les subscriptions', duration: '10 min', description: 'Tiers, emotes, stratégies de rétention' },
      { id: 6, title: 'Les bits : stratégies pour les maximiser', duration: '8 min', description: 'Cheers, polls, predictions' },
      { id: 7, title: 'Configurer les donations', duration: '6 min', description: 'PayPal, Streamlabs, alertes' },
      { id: 8, title: 'Programme d\'affiliation Amazon', duration: '12 min', description: 'Gagner sur chaque recommandation' },
      { id: 9, title: 'Créer une page sponsor attractive', duration: '8 min', description: 'Media kit professionnel' },
      { id: 10, title: 'Trouver des sponsors : où chercher', duration: '10 min', description: 'Plateformes et contacts directs' },
      { id: 11, title: 'Négocier avec un sponsor', duration: '12 min', description: 'Tarifs, contrats, red flags' },
      { id: 12, title: 'YouTube : monétisation AdSense', duration: '8 min', description: 'Requirements et optimisation' },
      { id: 13, title: 'YouTube Premium et Super Chat', duration: '5 min', description: 'Revenus additionnels YouTube' },
      { id: 14, title: 'Patreon : revenus récurrents', duration: '8 min', description: 'Créer et gérer une communauté payante' },
      { id: 15, title: 'Créer du merch qui se vend', duration: '10 min', description: 'Design, plateforme, prix' },
      { id: 16, title: 'Coaching et services payants', duration: '6 min', description: 'Monétiser ton expertise' },
      { id: 17, title: 'Déclaration fiscale des revenus', duration: '8 min', description: 'Ce que tu dois savoir légalement' },
      { id: 18, title: 'Créer ton plan de monétisation', duration: '6 min', description: 'Roadmap personnalisée' },
      { id: 19, title: 'Erreurs à éviter absolument', duration: '5 min', description: 'Pièges classiques de la monétisation' },
      { id: 20, title: 'Conclusion : vision long terme', duration: '4 min', description: 'Construire un business durable' },
    ],
  },
  {
    id: 7,
    slug: 'growth-hacking',
    number: '07',
    title: 'Growth Hacking Ultime',
    duration: '3h 00min',
    modules: 28,
    students: 25671,
    description: 'Algorithmes décryptés, stratégie clips, réseaux sociaux, collaborations',
    longDescription: `Maîtrise les algorithmes et booste ta croissance avec les techniques de growth hacking les plus efficaces utilisées par les top 1% des streamers. Ce cours intensif te révèle tout.

Comprends comment fonctionnent réellement les algorithmes Twitch, YouTube et TikTok. Crée du contenu viral qui se partage, développe une présence multiplateforme cohérente, et construis un réseau de collaborations stratégiques pour accélérer ta croissance.`,
    icon: 'FileText',
    color: 'from-fuchsia-400 via-pink-500 to-rose-600',
    difficulty: 'Expert',
    instructor: 'JOVE GARCIA Florian',
    instructorBio: 'Expert streaming et formateur passionné',
    lastUpdated: 'Décembre 2025',
    whatYouLearn: [
      'Comment fonctionnent les algorithmes',
      'Créer du contenu viral systématiquement',
      'Stratégie TikTok/Reels pour streamers',
      'Optimiser sa visibilité sur chaque plateforme',
      'Construire un réseau de collaborations',
      'Analyser ses stats pour progresser',
      'Growth hacking avancé et automation',
    ],
    requirements: [
      'Avoir une chaîne active',
      'Streamer régulièrement depuis 1+ mois',
      'Volonté de tester et itérer',
    ],
    resources: [
      { name: 'Social Media Kit Complet', url: '#', type: 'ZIP' },
      { name: 'Calendar Content 12 Mois', url: '#', type: 'Excel' },
      { name: 'Scripts Viraux TikTok (50+)', url: '#', type: 'Doc' },
      { name: 'Templates Clips Tendances', url: '#', type: 'ZIP' },
      { name: 'Checklist SEO Twitch/YouTube', url: '#', type: 'PDF' },
      { name: 'Guide Analytics Complet', url: '#', type: 'PDF' },
      { name: 'Template Pitch Collaboration', url: '#', type: 'Doc' },
    ],
    lessons: [
      { id: 1, title: 'Mindset Growth Hacking', duration: '5 min', description: 'L\'état d\'esprit des top streamers', isFree: true },
      { id: 2, title: 'Comment fonctionne l\'algo Twitch', duration: '12 min', description: 'Ce que Twitch pousse vraiment' },
      { id: 3, title: 'L\'algoritme YouTube décrypté', duration: '10 min', description: 'Watch time, CTR, rétention' },
      { id: 4, title: 'Comprendre TikTok et son algo', duration: '10 min', description: 'La viralité at scale' },
      { id: 5, title: 'Choisir les bons jeux/contenus', duration: '8 min', description: 'Ratio viewers/concurrence optimal' },
      { id: 6, title: 'Optimiser son profil pour la découverte', duration: '8 min', description: 'Titre, tags, description SEO' },
      { id: 7, title: 'L\'art du clip viral', duration: '10 min', description: 'Créer du contenu qui se partage' },
      { id: 8, title: 'Automatiser la création de clips', duration: '8 min', description: 'Outils et workflows' },
      { id: 9, title: 'Stratégie TikTok pour streamers', duration: '15 min', description: 'De 0 à 10k followers' },
      { id: 10, title: 'Repurposing : un contenu, 10 posts', duration: '10 min', description: 'Maximiser chaque stream' },
      { id: 11, title: 'Twitter/X : engagement maximal', duration: '8 min', description: 'Stratégie de présence optimale' },
      { id: 12, title: 'YouTube Shorts pour exploser', duration: '8 min', description: 'Le format qui fait la différence' },
      { id: 13, title: 'Instagram Reels gaming', duration: '6 min', description: 'Stratégie adaptée' },
      { id: 14, title: 'Discord comme outil de rétention', duration: '10 min', description: 'Créer une communauté fidèle' },
      { id: 15, title: 'Le networking entre streamers', duration: '8 min', description: 'Construire ton réseau' },
      { id: 16, title: 'Organiser des collaborations win-win', duration: '10 min', description: 'Raids, hosts, co-streams' },
      { id: 17, title: 'Les meilleurs horaires pour streamer', duration: '6 min', description: 'Data-driven scheduling' },
      { id: 18, title: 'Optimiser sa catégorie et tags', duration: '5 min', description: 'Être trouvé facilement' },
      { id: 19, title: 'Analytics Twitch : lire ses stats', duration: '10 min', description: 'Les KPIs qui comptent' },
      { id: 20, title: 'YouTube Studio analytics', duration: '8 min', description: 'Comprendre ses performances' },
      { id: 21, title: 'Outils d\'analyse externe', duration: '6 min', description: 'TwitchTracker, SullyGnome, etc.' },
      { id: 22, title: 'A/B testing tes thumbnails', duration: '6 min', description: 'Optimiser son CTR' },
      { id: 23, title: 'Paid promotion : faut-il payer ?', duration: '8 min', description: 'Ads Twitch/YouTube/TikTok' },
      { id: 24, title: 'Automation et outils de growth', duration: '10 min', description: 'Travailler plus intelligemment' },
      { id: 25, title: 'Events et challenges viraux', duration: '8 min', description: 'Créer du buzz' },
      { id: 26, title: 'Gérer un bad buzz', duration: '5 min', description: 'Crisis management pour streamers' },
      { id: 27, title: 'Créer son plan de croissance 90 jours', duration: '8 min', description: 'Ta roadmap personnalisée' },
      { id: 28, title: 'Conclusion : le marathon, pas le sprint', duration: '4 min', description: 'Vision long terme' },
    ],
  },
]

export function getCourseBySlug(slug: string): Course | undefined {
  return ACADEMY_COURSES.find(course => course.slug === slug)
}

export function getCourseById(id: number): Course | undefined {
  return ACADEMY_COURSES.find(course => course.id === id)
}
