// Stream Forge - Configurateur Data (2025 Research-Based)
// Sources: Tom's Hardware, PCMag, Eurogamer 2025

export interface Product {
  id: string
  name: string
  category: 'pc' | 'microphone' | 'camera' | 'light' | 'audio' | 'accessory'
  price: number
  description: string
  url: string
  affiliate: 'amazon' | 'ldlc' | 'aliexpress'
  image: string
  specs?: string[]
  model3d?: string // URL to GLB model
  suitableFor: string[] // ['gaming', 'irl', 'music', 'creative']
  tier: 'beginner' | 'intermediate' | 'advanced'
}

export const PRODUCTS: Product[] = [
  // === PC / ORDINATEURS ===
  {
    id: 'pc-beginner-1',
    name: 'PC Prémonté SAAV X1 Gaming',
    category: 'pc',
    price: 299,
    description: 'Ryzen 5 5600G, 16GB DDR4, SSD 500GB, Vega Graphics intégré',
    url: 'https://amazon.fr/pc-beginner',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=400',
    specs: ['Ryzen 5 5600G', '16GB RAM', 'Vega Graphics', 'SSD 500GB'],
    model3d: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf',
    suitableFor: ['gaming', 'creative'],
    tier: 'beginner',
  },
  {
    id: 'pc-beginner-2',
    name: 'Laptop Acer Aspire 5',
    category: 'pc',
    price: 549,
    description: 'Intel i5-12450H, 16GB, RTX 2050, parfait pour IRL streaming',
    url: 'https://amazon.fr/acer-aspire',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    specs: ['Intel i5-12450H', '16GB RAM', 'RTX 2050', 'Portable'],
    suitableFor: ['irl', 'creative'],
    tier: 'beginner',
  },
  {
    id: 'pc-intermediate-1',
    name: 'Config Custom Ryzen 7600X + RX 7600',
    category: 'pc',
    price: 849,
    description: 'Ryzen 7 7600X, RX 7600 8GB, 32GB DDR5, SSD 1TB NVMe',
    url: 'https://ldlc.com/custom-config',
    affiliate: 'ldlc',
    image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400',
    specs: ['Ryzen 7 7600X', 'RX 7600 8GB', '32GB DDR5', 'NVMe 1TB'],
    suitableFor: ['gaming', 'creative'],
    tier: 'intermediate',
  },
  {
    id: 'pc-advanced-1',
    name: 'Workstation i7-14700K + RTX 4070 Ti',
    category: 'pc',
    price: 1899,
    description: 'Intel i7-14700K, RTX 4070 Ti 12GB, 64GB DDR5, SSD 2TB + Capture Card',
    url: 'https://ldlc.com/workstation-pro',
    affiliate: 'ldlc',
    image: 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=400',
    specs: ['i7-14700K', 'RTX 4070 Ti 12GB', '64GB DDR5', '2TB NVMe', 'Elgato 4K60 S+'],
    suitableFor: ['gaming', 'creative', 'music'],
    tier: 'advanced',
  },

  // === MICROPHONES ===
  {
    id: 'mic-beginner-1',
    name: 'Joby Wavo Pod USB',
    category: 'microphone',
    price: 59,
    description: 'Micro USB compact, qualité studio, parfait pour débuter',
    url: 'https://amazon.fr/joby-wavo',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    specs: ['USB-C', 'Cardioïde', 'Compatible OBS', 'Portable'],
    suitableFor: ['gaming', 'irl', 'creative'],
    tier: 'beginner',
  },
  {
    id: 'mic-intermediate-1',
    name: '512 Audio Tempest',
    category: 'microphone',
    price: 129,
    description: 'Micro dynamique XLR/USB dual, son broadcast quality',
    url: 'https://amazon.fr/512-tempest',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    specs: ['XLR + USB', 'Dynamique', 'Filtre anti-pop intégré', 'RGB'],
    suitableFor: ['gaming', 'music', 'creative'],
    tier: 'intermediate',
  },
  {
    id: 'mic-intermediate-2',
    name: 'PreSonus Revelator',
    category: 'microphone',
    price: 169,
    description: 'Micro USB-C avec effets intégrés + loopback pour streamers',
    url: 'https://amazon.fr/presonus-revelator',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    specs: ['USB-C', 'Effets Fat Channel', 'Loopback', 'Contrôle vocal'],
    suitableFor: ['music', 'gaming'],
    tier: 'intermediate',
  },
  {
    id: 'mic-advanced-1',
    name: 'Shure SM7B + Interface Focusrite',
    category: 'microphone',
    price: 489,
    description: 'Le légendaire SM7B avec interface audio Scarlett Solo',
    url: 'https://amazon.fr/shure-sm7b-bundle',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    specs: ['XLR', 'Dynamique broadcast', 'Interface Focusrite', 'Filtre switchable'],
    suitableFor: ['music', 'creative'],
    tier: 'advanced',
  },

  // === CAMÉRAS ===
  {
    id: 'cam-beginner-1',
    name: 'Logitech C922 Pro',
    category: 'camera',
    price: 79,
    description: 'Webcam 1080p 30fps, autofocus, parfaite pour débuter',
    url: 'https://amazon.fr/logitech-c922',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1606980639964-d4a6087d1e15?w=400',
    specs: ['1080p 30fps', 'Autofocus', 'Stéréo mic', 'Trépied inclus'],
    suitableFor: ['gaming', 'creative'],
    tier: 'beginner',
  },
  {
    id: 'cam-intermediate-1',
    name: 'Razer Kiyo Pro',
    category: 'camera',
    price: 149,
    description: 'Webcam 1080p 60fps HDR, capteur Sony STARVIS',
    url: 'https://amazon.fr/razer-kiyo-pro',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1606980639964-d4a6087d1e15?w=400',
    specs: ['1080p 60fps', 'HDR', 'Sony STARVIS', 'Low light king'],
    suitableFor: ['gaming', 'irl', 'creative'],
    tier: 'intermediate',
  },
  {
    id: 'cam-advanced-1',
    name: 'Razer Kiyo Pro Ultra 4K',
    category: 'camera',
    price: 299,
    description: 'Webcam 4K 24fps / 1080p 60fps, capteur 1/1.2", f/1.7',
    url: 'https://amazon.fr/razer-kiyo-ultra',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1606980639964-d4a6087d1e15?w=400',
    specs: ['4K 24fps', '1080p 60fps', 'Large sensor', 'Uncompressed'],
    suitableFor: ['creative', 'irl'],
    tier: 'advanced',
  },
  {
    id: 'cam-advanced-2',
    name: 'Sony ZV-E10 + Sigma 16mm',
    category: 'camera',
    price: 899,
    description: 'Caméra mirrorless APS-C pour qualité cinéma',
    url: 'https://amazon.fr/sony-zve10',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1606980639964-d4a6087d1e15?w=400',
    specs: ['24MP APS-C', '4K 30fps', 'Sigma 16mm f/1.4', 'HDMI clean'],
    suitableFor: ['creative', 'irl'],
    tier: 'advanced',
  },

  // === LUMIÈRES ===
  {
    id: 'light-beginner-1',
    name: 'Ring Light LED 10"',
    category: 'light',
    price: 29,
    description: 'Anneau lumineux LED avec trépied, 3 modes couleur',
    url: 'https://amazon.fr/ring-light',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1557980147-7862c2c2c581?w=400',
    specs: ['10 pouces', 'Dimmable', '3200K-5600K', 'USB powered'],
    suitableFor: ['gaming', 'irl', 'creative'],
    tier: 'beginner',
  },
  {
    id: 'light-intermediate-1',
    name: 'Elgato Key Light Mini',
    category: 'light',
    price: 89,
    description: 'Lumière LED compacte pilotable via Stream Deck',
    url: 'https://amazon.fr/elgato-mini',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1557980147-7862c2c2c581?w=400',
    specs: ['800 lumen', '2900K-7000K', 'WiFi control', 'Compact'],
    suitableFor: ['gaming', 'creative'],
    tier: 'intermediate',
  },
  {
    id: 'light-advanced-1',
    name: 'Elgato Key Light Air x2 + Softbox',
    category: 'light',
    price: 259,
    description: 'Setup pro avec 2 Key Light Air + diffuseurs softbox',
    url: 'https://amazon.fr/elgato-air-bundle',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1557980147-7862c2c2c581?w=400',
    specs: ['1400 lumen x2', 'WiFi', 'Softbox diffusers', '2 lights'],
    suitableFor: ['creative', 'irl'],
    tier: 'advanced',
  },

  // === AUDIO INTERFACES ===
  {
    id: 'audio-intermediate-1',
    name: 'Focusrite Scarlett Solo 4th Gen',
    category: 'audio',
    price: 129,
    description: 'Interface audio USB-C pour micro XLR + instrument',
    url: 'https://amazon.fr/focusrite-solo',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400',
    specs: ['USB-C', '1 XLR + 1 Jack', 'Air preamp', '24bit/192kHz'],
    suitableFor: ['music'],
    tier: 'intermediate',
  },
  {
    id: 'audio-advanced-1',
    name: 'TC Helicon GoXLR',
    category: 'audio',
    price: 449,
    description: 'Console de mixage ultime pour streamers',
    url: 'https://amazon.fr/goxlr',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400',
    specs: ['4 canaux', 'Voice effects', 'Faders motorisés', 'Routing complet'],
    suitableFor: ['gaming', 'music'],
    tier: 'advanced',
  },

  // === ACCESSOIRES ===
  {
    id: 'acc-headset-1',
    name: 'SteelSeries Arctis Nova 1',
    category: 'accessory',
    price: 59,
    description: 'Casque gaming confortable pour sessions longues',
    url: 'https://amazon.fr/arctis-nova',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=400',
    specs: ['3.5mm', 'Léger', 'Mic rétractable', 'Multi-platform'],
    suitableFor: ['gaming'],
    tier: 'beginner',
  },
  {
    id: 'acc-greenscreen-1',
    name: 'Green Screen Portable Pliable',
    category: 'accessory',
    price: 39,
    description: 'Fond vert pop-up pour chroma key parfait',
    url: 'https://amazon.fr/green-screen',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1579762593483-2a0267d47c93?w=400',
    specs: ['142x195cm', 'Pliable', 'Anti-reflet', 'Sac inclus'],
    suitableFor: ['gaming', 'irl'],
    tier: 'beginner',
  },
  {
    id: 'acc-streamdeck-1',
    name: 'Elgato Stream Deck MK.2',
    category: 'accessory',
    price: 149,
    description: '15 touches LCD personnalisables pour contrôle total',
    url: 'https://amazon.fr/streamdeck',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
    specs: ['15 LCD keys', 'USB-C', 'OBS integration', 'Plugins'],
    suitableFor: ['gaming', 'creative'],
    tier: 'intermediate',
  },
  {
    id: 'acc-armmic-1',
    name: 'Bras de Micro Articulé Rode PSA1+',
    category: 'accessory',
    price: 109,
    description: 'Bras articulé premium pour micro broadcast',
    url: 'https://amazon.fr/rode-psa1',
    affiliate: 'amazon',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    specs: ['Rotation 360°', 'Ressorts renforcés', 'Câbles intégrés', 'Premium'],
    suitableFor: ['music', 'creative'],
    tier: 'intermediate',
  },
]

export const BUDGET_OPTIONS = [
  {
    id: 'budget-300',
    value: 300,
    label: '300€ - Budget Débutant',
    description: 'Setup complet pour commencer sans se ruiner',
    color: 'from-green-500 to-emerald-500',
    icon: '💚',
  },
  {
    id: 'budget-800',
    value: 800,
    label: '800€ - Intermédiaire',
    description: 'Qualité pro sans compromis majeurs',
    color: 'from-blue-500 to-cyan-500',
    icon: '💙',
  },
  {
    id: 'budget-1500',
    value: 1500,
    label: '1500€+ - Avancé',
    description: 'Setup premium pour résultats exceptionnels',
    color: 'from-purple-500 to-pink-500',
    icon: '💜',
  },
]

export const CONTENT_TYPES = [
  {
    id: 'gaming',
    label: 'Gaming',
    description: 'Jeux vidéo, e-sport, let\'s play',
    icon: '🎮',
    color: 'from-red-500 to-orange-500',
    priorities: ['pc', 'microphone', 'camera'],
  },
  {
    id: 'irl',
    label: 'IRL / Vlog',
    description: 'Sorties, voyages, just chatting',
    icon: '🎥',
    color: 'from-cyan-500 to-blue-500',
    priorities: ['camera', 'microphone', 'light'],
  },
  {
    id: 'music',
    label: 'Musique / ASMR',
    description: 'Audio haute qualité, production',
    icon: '🎵',
    color: 'from-purple-500 to-violet-500',
    priorities: ['microphone', 'audio', 'light'],
  },
  {
    id: 'creative',
    label: 'Créatif / Art',
    description: 'Design, montage, création',
    icon: '🎨',
    color: 'from-pink-500 to-rose-500',
    priorities: ['pc', 'camera', 'light'],
  },
]

export const AESTHETIC_PREFS = [
  {
    id: 'minimal',
    label: 'Minimaliste',
    description: 'Clean, sobre, efficace',
    icon: '⚪',
    priceModifier: 0,
  },
  {
    id: 'rgb',
    label: 'RGB Gamer',
    description: 'Lumières, couleurs, gaming vibes',
    icon: '🌈',
    priceModifier: 50, // Add RGB accessories
  },
  {
    id: 'pro',
    label: 'Pro Studio',
    description: 'Élégant, professionnel, broadcast',
    icon: '⭐',
    priceModifier: 100, // Better quality items
  },
]

export const SETUP_PREFS = [
  {
    id: 'portable',
    label: 'Setup Portable',
    value: 'portable',
  },
  {
    id: 'multi',
    label: 'Multi-joueurs (plusieurs micros)',
    value: 'multi',
  },
  {
    id: 'greenscreen',
    label: 'Green Screen',
    value: 'greenscreen',
  },
]
