// Stream Forge - Matériel Ultime 2025
// Base de données produits réels avec images fonctionnelles

export interface Product {
  id: number
  name: string
  brand: string
  category: 'cameras' | 'micros' | 'audio' | 'eclairage' | 'pc' | 'ecrans'
  price: number
  rating: number
  reviews: number
  trending: boolean
  budget: 'debutant' | 'intermediaire' | 'pro'
  image: string
  modelUrl?: string
  description: string
  specs: string[]
  url: string
  affiliate: 'Amazon' | 'LDLC' | 'Materiel.net'
  inStock: boolean
}

export const PRODUCTS: Product[] = [
  // === CAMÉRAS ===
  {
    id: 1,
    name: 'Facecam Pro 4K60',
    brand: 'Elgato',
    category: 'cameras',
    price: 299,
    rating: 4.8,
    reviews: 1201,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=300&fit=crop',
    description: 'Caméra 4K60 avec capteur Sony, HDR et auto-focus ultra-rapide',
    specs: ['4K 60fps', 'HDR10', 'Sony STARVIS 2', 'USB-C 3.2', 'Champ 82°'],
    url: 'https://www.amazon.fr/s?k=Elgato+Facecam+Pro',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 2,
    name: 'Kiyo Pro Ultra',
    brand: 'Razer',
    category: 'cameras',
    price: 299,
    rating: 4.9,
    reviews: 2847,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1606980639964-d4a6087d1e15?w=400&h=300&fit=crop',
    description: 'Capteur 1/1.2" 4K HDR, le meilleur pour low light',
    specs: ['4K 30fps uncompressed', 'f/1.7', 'AI auto-framing', 'HDR', 'Studio-grade'],
    url: 'https://www.amazon.fr/s?k=Razer+Kiyo+Pro+Ultra',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 3,
    name: 'Brio 505',
    brand: 'Logitech',
    category: 'cameras',
    price: 89,
    rating: 4.5,
    reviews: 3421,
    trending: false,
    budget: 'debutant',
    image: 'https://images.unsplash.com/photo-1622959587408-ea767aabd98d?w=400&h=300&fit=crop',
    description: 'Webcam Full HD abordable avec excellente qualité',
    specs: ['1080p 30fps', 'Auto-focus', 'Correction lumière', 'Micro intégré', 'USB-C'],
    url: 'https://www.amazon.fr/s?k=Logitech+Brio+505',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 4,
    name: 'C920s HD Pro',
    brand: 'Logitech',
    category: 'cameras',
    price: 79,
    rating: 4.6,
    reviews: 12453,
    trending: false,
    budget: 'debutant',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=300&fit=crop',
    description: 'Le classique indémodable, toujours efficace en 2025',
    specs: ['1080p 30fps', 'Autofocus', '78° FOV', '2 micros stéréo', 'Plug & Play'],
    url: 'https://www.amazon.fr/s?k=Logitech+C920s',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 5,
    name: 'ZV-E10 II',
    brand: 'Sony',
    category: 'cameras',
    price: 899,
    rating: 5.0,
    reviews: 456,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=300&fit=crop',
    description: 'Mirrorless APS-C pour qualité cinéma en streaming',
    specs: ['4K 60fps', 'APS-C 26MP', 'Eye-AF', 'HDMI clean out', 'Objectifs interchangeables'],
    url: 'https://www.amazon.fr/s?k=Sony+ZV-E10',
    affiliate: 'Amazon',
    inStock: true,
  },

  // === MICROPHONES ===
  {
    id: 6,
    name: 'SM7B',
    brand: 'Shure',
    category: 'micros',
    price: 389,
    rating: 4.9,
    reviews: 8421,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=300&fit=crop',
    description: 'Le légendaire micro broadcast, utilisé par 90% des top streamers',
    specs: ['XLR dynamique', 'Broadcast quality', 'Filtre anti-pop intégré', 'Suspension pneumatique', 'Warm sound'],
    url: 'https://www.amazon.fr/s?k=Shure+SM7B',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 7,
    name: 'Wave:3',
    brand: 'Elgato',
    category: 'micros',
    price: 159,
    rating: 4.7,
    reviews: 3201,
    trending: true,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=300&fit=crop',
    description: 'Micro USB cardioïde avec Clipguard anti-distortion',
    specs: ['USB-C', 'Cardioïde', 'Clipguard', 'Mute tactile', 'Contrôle gain'],
    url: 'https://www.amazon.fr/s?k=Elgato+Wave+3',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 8,
    name: 'Yeti X',
    brand: 'Blue',
    category: 'micros',
    price: 169,
    rating: 4.6,
    reviews: 5632,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=400&h=300&fit=crop',
    description: 'Micro USB légendaire avec 4 patterns, LED metering',
    specs: ['USB', '4 polar patterns', 'LED metering', 'Blue VO!CE', 'Logitech G HUB'],
    url: 'https://www.amazon.fr/s?k=Blue+Yeti+X',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 9,
    name: 'Seiren V2 Pro',
    brand: 'Razer',
    category: 'micros',
    price: 149,
    rating: 4.5,
    reviews: 1832,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1558470598-a5dda9640f68?w=400&h=300&fit=crop',
    description: 'Micro USB dynamique avec filtre passe-haut intégré',
    specs: ['USB', 'Dynamique', 'Filtre passe-haut', 'Monitoring zéro latence', 'Shock mount'],
    url: 'https://www.amazon.fr/s?k=Razer+Seiren+V2+Pro',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 10,
    name: 'QuadCast S',
    brand: 'HyperX',
    category: 'micros',
    price: 129,
    rating: 4.8,
    reviews: 4523,
    trending: true,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1593697820754-1bb24c2e0b42?w=400&h=300&fit=crop',
    description: 'Micro USB RGB avec support anti-vibration intégré',
    specs: ['USB-C', 'RGB customizable', '4 polar patterns', 'Pop filter', 'Tap-to-mute'],
    url: 'https://www.amazon.fr/s?k=HyperX+QuadCast+S',
    affiliate: 'Amazon',
    inStock: true,
  },

  // === AUDIO (Interfaces & Mixeurs) ===
  {
    id: 11,
    name: 'GoXLR',
    brand: 'TC Helicon',
    category: 'audio',
    price: 449,
    rating: 4.9,
    reviews: 2341,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1558470598-a5dda9640f68?w=400&h=300&fit=crop',
    description: 'La console de mixage ultime pour streamers',
    specs: ['4 faders motorisés', 'Voice FX', 'Mute button', 'Sample pads', 'Multi-routing'],
    url: 'https://www.amazon.fr/s?k=TC+Helicon+GoXLR',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 12,
    name: 'Scarlett 2i2 4th Gen',
    brand: 'Focusrite',
    category: 'audio',
    price: 189,
    rating: 4.8,
    reviews: 8932,
    trending: true,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=400&h=300&fit=crop',
    description: 'Interface audio USB-C best-seller mondial',
    specs: ['USB-C', '2 préamps Air', '192kHz/24bit', 'Monitoring direct', 'Loopback'],
    url: 'https://www.amazon.fr/s?k=Focusrite+Scarlett+2i2',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 13,
    name: 'Wave XLR',
    brand: 'Elgato',
    category: 'audio',
    price: 159,
    rating: 4.7,
    reviews: 1543,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1563330232-57114bb0823c?w=400&h=300&fit=crop',
    description: 'Interface XLR avec Clipguard et control tactile',
    specs: ['USB-C', 'XLR 48V', 'Clipguard', 'Capacitive mute', 'Wave Link'],
    url: 'https://www.amazon.fr/s?k=Elgato+Wave+XLR',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 14,
    name: 'Volt 2',
    brand: 'Universal Audio',
    category: 'audio',
    price: 189,
    rating: 4.9,
    reviews: 721,
    trending: true,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=400&h=300&fit=crop',
    description: 'Interface avec préamps UA vintage légendaires',
    specs: ['USB-C', 'Vintage preamps', 'Compressor 76', '192kHz', 'Studio sound'],
    url: 'https://www.amazon.fr/s?k=Universal+Audio+Volt+2',
    affiliate: 'Amazon',
    inStock: true,
  },

  // === ÉCLAIRAGE ===
  {
    id: 15,
    name: 'Key Light Air',
    brand: 'Elgato',
    category: 'eclairage',
    price: 129,
    rating: 4.8,
    reviews: 5621,
    trending: true,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1557980147-7862c2c2c581?w=400&h=300&fit=crop',
    description: 'Panneau LED WiFi 1400 lumens, contrôle Stream Deck',
    specs: ['1400 lumen', '2900K-7000K', 'WiFi control', 'App mobile', 'Edge-lit'],
    url: 'https://www.amazon.fr/s?k=Elgato+Key+Light+Air',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 16,
    name: 'Key Light',
    brand: 'Elgato',
    category: 'eclairage',
    price: 199,
    rating: 4.9,
    reviews: 8234,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1504194921103-f8b80cadd5e4?w=400&h=300&fit=crop',
    description: 'Version pro 2800 lumens pour studios exigeants',
    specs: ['2800 lumen', '2900K-7000K', 'WiFi', 'Premium build', 'Broadcast grade'],
    url: 'https://www.amazon.fr/s?k=Elgato+Key+Light',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 17,
    name: 'Litra Glow',
    brand: 'Logitech',
    category: 'eclairage',
    price: 59,
    rating: 4.6,
    reviews: 2243,
    trending: false,
    budget: 'debutant',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=300&fit=crop',
    description: 'Lumière douce LED clipsable pour webcam',
    specs: ['LED diffuse', 'USB-C', 'TrueSoft', 'Clip universel', 'Réglable'],
    url: 'https://www.amazon.fr/s?k=Logitech+Litra+Glow',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 18,
    name: 'Ring Light 18"',
    brand: 'Neewer',
    category: 'eclairage',
    price: 59,
    rating: 4.5,
    reviews: 7832,
    trending: false,
    budget: 'debutant',
    image: 'https://images.unsplash.com/photo-1596142883920-db56a3fb9e8d?w=400&h=300&fit=crop',
    description: 'Anneau LED dimmable avec trépied, excellent rapport qualité/prix',
    specs: ['18 pouces', 'Dimmable', '3200K-5600K', 'Trépied 2m', 'Télécommande'],
    url: 'https://www.amazon.fr/s?k=Neewer+Ring+Light+18',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 19,
    name: 'Light Strip',
    brand: 'Elgato',
    category: 'eclairage',
    price: 89,
    rating: 4.7,
    reviews: 2134,
    trending: true,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1614624532983-4ce03382d63d?w=400&h=300&fit=crop',
    description: 'Bande LED RGBWW pour ambiance setup gaming',
    specs: ['RGBWW', '2m extensible', 'WiFi', 'Stream Deck', '16M couleurs'],
    url: 'https://www.amazon.fr/s?k=Elgato+Light+Strip',
    affiliate: 'Amazon',
    inStock: true,
  },

  // === PC & CONFIGS ===
  {
    id: 20,
    name: 'PC Streaming Haut de Gamme',
    brand: 'LDLC',
    category: 'pc',
    price: 2499,
    rating: 5.0,
    reviews: 234,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=400&h=300&fit=crop',
    description: 'Ryzen 9 7950X + RTX 4080 Super, encode x264 + jeu ultra simultané',
    specs: ['Ryzen 9 7950X', 'RTX 4080 Super', '64GB DDR5', '2TB NVMe Gen4', 'Watercooling'],
    url: 'https://www.ldlc.com/informatique/ordinateur-de-bureau/pc-gamer/c4266/',
    affiliate: 'LDLC',
    inStock: true,
  },
  {
    id: 21,
    name: 'PC Streaming Gaming',
    brand: 'LDLC',
    category: 'pc',
    price: 1899,
    rating: 4.9,
    reviews: 567,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=400&h=300&fit=crop',
    description: 'Ryzen 7 7800X3D + RTX 4070 Ti, le meilleur pour gaming + stream',
    specs: ['Ryzen 7 7800X3D', 'RTX 4070 Ti', '32GB DDR5', '1TB NVMe', 'Air cooling'],
    url: 'https://www.ldlc.com/informatique/ordinateur-de-bureau/pc-gamer/c4266/',
    affiliate: 'LDLC',
    inStock: true,
  },
  {
    id: 22,
    name: 'PC Streaming Mid-Range',
    brand: 'LDLC',
    category: 'pc',
    price: 1199,
    rating: 4.7,
    reviews: 892,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1625225233840-695456021cde?w=400&h=300&fit=crop',
    description: 'Intel i5-14600K + RTX 4060 Ti, parfait pour 1080p stream + jeu',
    specs: ['i5-14600K', 'RTX 4060 Ti 16GB', '32GB DDR5', '1TB NVMe', 'B760 chipset'],
    url: 'https://www.ldlc.com/informatique/ordinateur-de-bureau/pc-gamer/c4266/',
    affiliate: 'LDLC',
    inStock: true,
  },
  {
    id: 23,
    name: 'PC Streaming Entrée de Gamme',
    brand: 'LDLC',
    category: 'pc',
    price: 899,
    rating: 4.6,
    reviews: 1234,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?w=400&h=300&fit=crop',
    description: 'Ryzen 5 7600 + RX 7600, excellent pour débuter le streaming',
    specs: ['Ryzen 5 7600', 'RX 7600 8GB', '16GB DDR5', '500GB NVMe', 'B650 chipset'],
    url: 'https://www.ldlc.com/informatique/ordinateur-de-bureau/pc-gamer/c4266/',
    affiliate: 'LDLC',
    inStock: true,
  },
  {
    id: 24,
    name: 'Mini PC SER5 MAX',
    brand: 'Beelink',
    category: 'pc',
    price: 449,
    rating: 4.5,
    reviews: 2341,
    trending: false,
    budget: 'debutant',
    image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&h=300&fit=crop',
    description: 'Mini PC Ryzen 7 5800H compact pour streaming léger',
    specs: ['Ryzen 7 5800H', 'Radeon Vega', '16GB DDR4', '500GB NVMe', 'Ultra-compact'],
    url: 'https://www.amazon.fr/s?k=Beelink+SER5+MAX',
    affiliate: 'Amazon',
    inStock: true,
  },

  // === ÉCRANS ===
  {
    id: 25,
    name: 'ROG Swift OLED PG27AQDM',
    brand: 'ASUS',
    category: 'ecrans',
    price: 899,
    rating: 5.0,
    reviews: 432,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=300&fit=crop',
    description: 'OLED 1440p 240Hz, le summum pour gaming + monitoring stream',
    specs: ['27" OLED', '1440p 240Hz', '0.03ms', 'HDR True Black 400', 'G-Sync'],
    url: 'https://www.amazon.fr/s?k=ASUS+ROG+Swift+OLED+PG27AQDM',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 26,
    name: 'PD3220U DesignVue',
    brand: 'BenQ',
    category: 'ecrans',
    price: 649,
    rating: 4.9,
    reviews: 823,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=400&h=300&fit=crop',
    description: '4K IPS 60Hz calibré usine pour créateurs de contenu',
    specs: ['32" 4K IPS', '60Hz', 'DCI-P3 95%', 'Calibré usine', 'USB-C 65W'],
    url: 'https://www.amazon.fr/s?k=BenQ+PD3220U',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 27,
    name: '27GP850-B UltraGear',
    brand: 'LG',
    category: 'ecrans',
    price: 349,
    rating: 4.7,
    reviews: 3421,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400&h=300&fit=crop',
    description: 'IPS 27" 1440p 165Hz excellent rapport qualité/prix',
    specs: ['27" Nano IPS', '1440p 165Hz', '1ms GtG', 'G-Sync Compatible', 'HDR400'],
    url: 'https://www.amazon.fr/s?k=LG+27GP850',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 28,
    name: '24G2SP',
    brand: 'AOC',
    category: 'ecrans',
    price: 149,
    rating: 4.5,
    reviews: 5621,
    trending: false,
    budget: 'debutant',
    image: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=400&h=300&fit=crop',
    description: '24" IPS 1080p 165Hz parfait pour débuter',
    specs: ['24" IPS', '1080p 165Hz', '1ms MPRT', 'FreeSync Premium', 'Frameless'],
    url: 'https://www.amazon.fr/s?k=AOC+24G2SP',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 29,
    name: 'Odyssey G5 34"',
    brand: 'Samsung',
    category: 'ecrans',
    price: 449,
    rating: 4.8,
    reviews: 1432,
    trending: true,
    budget: 'pro',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    description: 'Ultrawide 34" 1440p pour immersion totale',
    specs: ['34" VA curved', '3440x1440 165Hz', '1ms', 'HDR10', 'FreeSync Premium'],
    url: 'https://www.amazon.fr/s?k=Samsung+Odyssey+G5+34',
    affiliate: 'Amazon',
    inStock: true,
  },
  {
    id: 30,
    name: 'ZenScreen MB16ACV',
    brand: 'ASUS',
    category: 'ecrans',
    price: 249,
    rating: 4.6,
    reviews: 921,
    trending: false,
    budget: 'intermediaire',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop',
    description: 'Écran portable IPS 15.6" pour setup nomade',
    specs: ['15.6" IPS', '1080p 60Hz', 'USB-C power', 'Webcam intégrée', 'Smart Case'],
    url: 'https://www.amazon.fr/s?k=ASUS+ZenScreen+MB16ACV',
    affiliate: 'Amazon',
    inStock: true,
  },
]

export const CATEGORIES = [
  { id: 'tout', name: 'Tout', icon: 'Filter' },
  { id: 'cameras', name: 'Caméras', icon: 'Camera' },
  { id: 'micros', name: 'Micros', icon: 'Mic' },
  { id: 'audio', name: 'Audio', icon: 'Headphones' },
  { id: 'eclairage', name: 'Éclairage', icon: 'Lightbulb' },
  { id: 'pc', name: 'PC/Config', icon: 'Cpu' },
  { id: 'ecrans', name: 'Écrans', icon: 'Monitor' },
] as const

export const BUDGET_FILTERS = [
  { id: 'debutant', label: 'Débutant', color: 'bg-green-500' },
  { id: 'intermediaire', label: 'Intermédiaire', color: 'bg-blue-500' },
  { id: 'pro', label: 'Pro', color: 'bg-purple-500' },
] as const

export const SORT_OPTIONS = [
  { id: 'trending', label: 'Tendance', icon: '🔥' },
  { id: 'rating', label: 'Notes', icon: '⭐' },
  { id: 'price-asc', label: 'Prix croissant', icon: '💰' },
  { id: 'price-desc', label: 'Prix décroissant', icon: '💎' },
  { id: 'reviews', label: 'Plus commentés', icon: '💬' },
] as const
